### ISSUE TITLE
As a product owner I want this program to work on all platforms

### ISSUE THREAD

**Issue by MuffinSmith** [MuffinSmith/ProjectThinggy#16]
The program should be able to run on windows, mac, and Linux computers

**Comment by AntiGravPilot** [comment]
There shouldn't be anything that we have to do for this one; So long as the project builds on one platform, it should build for others assuming  the user has those platforms and a build utility. Unless I'm missing something?

**Comment by vain3219** [comment]
I doubt he expects us to actually make the program runable on those OS. I think he just wants us to put it in the pamphlet that it will run on those OS.
